import { normalizePhoneNumber } from '../utils/phoneUtils.js';
import { formatMessageWithDate, getTimeBasedGreeting } from '../utils/messageFormatter.js';
import { getCurrentDate } from '../utils/dateUtils.js';
import * as redisService from '../services/redisService.js';
import * as openaiService from '../services/openaiService.js';
import * as whatsappService from '../services/whatsappService.js';
import * as mediaService from '../services/mediaService.js';
import * as audioService from '../services/audioService.js';
import * as onboardingService from '../services/onboardingService.js';
import * as anamneseService from '../services/anamneseService.js';
import * as flowService from '../services/flowService.js';
import * as alertService from '../services/alertService.js';
import * as paymentService from '../services/paymentService.js';
import { config } from '../config/index.js';
import moment from 'moment-timezone';

// Map para armazenar mensagens temporariamente
const messageBuffers = new Map();
const bufferTimeouts = new Map();

export const processMessage = async (message, profileName, phoneNumberId, res) => {
  try {
    const phoneNumber = normalizePhoneNumber(message.from);
    console.log("Normalized phone number:", phoneNumber);

    // Verificar se é mensagem duplicada
    const existingMessageData = await redisService.getMessageData(message.id);
    
    if (existingMessageData && existingMessageData.timestamp === String(message.timestamp)) {
      console.log("Mensagem duplicada ignorada.");
      if (!res.headersSent) {
        res.sendStatus(200);
      }
      return;
    }

    // Obter ou criar threadId
    let threadId = await redisService.getThreadId(phoneNumber);

    if (!threadId) {
      threadId = await createNewThread(phoneNumber, message, profileName);
    }

    // Salvar mensagem no Redis
    await saveMessageToRedis(message, phoneNumber, threadId, profileName);

    // Processar diferentes tipos de mensagem
    if (message.text) {
      await handleTextMessage(message, phoneNumber, profileName, phoneNumberId, res, threadId);
    } else if (message.audio) {
      await handleAudioMessage(message, phoneNumber, profileName, phoneNumberId, res, threadId);
    } else if (message.image) {
      await handleImageMessage(message, phoneNumber, profileName, phoneNumberId, res, threadId);
    } else if (message.document && message.document.mime_type === "application/pdf") {
      await handlePdfMessage(message, phoneNumber, profileName, phoneNumberId, res, threadId);
    } else {
      // Tipo de mensagem não suportado
      console.log(`Tipo de mensagem não suportado: ${message.type}`);
      if (!res.headersSent) {
        res.sendStatus(200);
      }
    }
  } catch (error) {
    console.error("Error processing message:", error);
    throw error;
  }
};

async function createNewThread(phoneNumber, message, profileName) {
  console.log(`Nenhum threadId encontrado para o número ${phoneNumber}, criando um novo thread...`);
  const greeting = getTimeBasedGreeting();
  
  // Adiciona contexto explícito sobre o nome do usuário
  const userInfo = `[SISTEMA: O nome do usuário é ${profileName}]\n`;
  
  const formattedMessage = formatMessageWithDate(
    `${greeting} ${message.text ? message.text.body : ''}`,
    message.timestamp,
    profileName
  );

  const thread = await openaiService.createThread(
    `${userInfo}${formattedMessage}`, 
    phoneNumber
  );
  const threadId = thread.id;
  
  await redisService.setThreadId(phoneNumber, threadId);
  console.log(`Novo thread ID ${threadId} criado e armazenado para ${phoneNumber}`);
  
  return threadId;
}

async function saveMessageToRedis(message, phoneNumber, threadId, profileName) {
  const messageData = {
    id: message.id ? message.id.toString() : '',
    timestamp: message.timestamp ? message.timestamp.toString() : '',
    phoneNumber: phoneNumber ? phoneNumber.toString() : '',
    content: message.text && message.text.body ? message.text.body : '',
    assistantId: config.openai.assistantId || '',
    aiPhoneNumber: config.whatsapp.aiPhoneNumber || '',
    threadId: threadId ? threadId.toString() : '',
    createdAt: Date.now().toString(),
    localTime: moment().tz("America/Sao_Paulo").format('HH:mm:ss'),
    location: message.location ? { lat: message.location.latitude, long: message.location.longitude } : null,
    type: message.type ? message.type : 'text',
    status: message.status ? message.status : 'unknown',
    isAutoGenerated: false,
    deviceInfo: message.device ? message.device : 'unknown',
    userName: profileName
  };

  await redisService.saveMessage(message.id, messageData);
  console.log(`Message ID ${message.id} added to Redis with threadId ${threadId}`);
}

async function handleTextMessage(message, phoneNumber, profileName, phoneNumberId, res, threadId) {
  const userMessage = message.text.body.toLowerCase();

  // Comando especial para apagar thread
  if (userMessage.includes("apagar thread_id")) {
    await handleDeleteThreadCommand(phoneNumber, phoneNumberId, message.from, res);
    return;
  }

  // Comando especial para resetar memória
  if (userMessage.includes("/reset") || userMessage.includes("reset") || userMessage.includes("zerar memória")) {
    await resetUserMemory(phoneNumber, phoneNumberId, res);
    return;
  }

  // Verificar se usuário quer iniciar o serviço
  if (userMessage.includes("quero iniciar") || userMessage.includes("iniciar") || 
      userMessage.includes("começar") || userMessage.includes("comecar")) {
    console.log(`🚀 Usuário ${phoneNumber} solicitou início do serviço`);
    await handleStartRequest(phoneNumber, phoneNumberId, profileName, res);
    return;
  }

  // Verificar se usuário quer um plano específico
  const requestedPlan = paymentService.detectPlanFromMessage(userMessage);
  if (requestedPlan) {
    console.log(`💳 Usuário ${phoneNumber} solicitou plano: ${requestedPlan}`);
    await handlePlanRequest(phoneNumber, phoneNumberId, requestedPlan, res);
    return;
  }

  // Verificar se está em processo de onboarding/consentimento
  const onboardingStatus = await onboardingService.getOnboardingStatus(phoneNumber);
  if (onboardingStatus && onboardingStatus.status === 'started') {
    await handleOnboardingResponse(phoneNumber, phoneNumberId, userMessage, res);
    return;
  }

  // Verificar se está em processo de anamnese (Flow)
  const flowStatus = await flowService.getFlowStatus(phoneNumber);
  if (flowStatus && flowStatus.status === 'started') {
    // Aguardar resposta do Flow via webhook
    console.log('Usuário está em processo de Flow, aguardando resposta via webhook');
    return;
  }

  // Verificar se está em processo de anamnese (tradicional)
  const anamneseStatus = await anamneseService.getAnamneseData(phoneNumber);
  if (anamneseStatus && anamneseStatus.status === 'started') {
    await anamneseService.processAnamneseAnswer(phoneNumber, userMessage);
    return;
  }

  // Buffer de mensagens
  if (!messageBuffers.has(phoneNumber)) {
    messageBuffers.set(phoneNumber, []);
  }

  messageBuffers.get(phoneNumber).push(message.text.body);

  if (bufferTimeouts.has(phoneNumber)) {
    clearTimeout(bufferTimeouts.get(phoneNumber));
  }

  // Processar mensagens após 4 segundos
  bufferTimeouts.set(phoneNumber, setTimeout(async () => {
    try {
      const bufferedMessages = messageBuffers.get(phoneNumber).join(' ');
      messageBuffers.delete(phoneNumber);
      bufferTimeouts.delete(phoneNumber);

      const currentDate = getCurrentDate();
      
      // Adiciona contexto do nome do usuário na mensagem
      const messageWithContext = `[Usuário ${profileName} diz:] ${bufferedMessages} [Data: ${currentDate}]`;
      
      const formattedMessage = formatMessageWithDate(
        messageWithContext,
        message.timestamp,
        profileName
      );

      // Armazenar mensagem do usuário
      await redisService.storeMessageInConversation(phoneNumber, threadId, {
        role: 'user',
        content: formattedMessage,
        timestamp: Date.now()
      });

      // Verificar e gerenciar tokens
      let totalTokens = 0;
      try {
        totalTokens = await openaiService.getTokenUsage(threadId);
      } catch (tokenErr) {
        console.warn('Falha ao obter uso de tokens (continuando):', tokenErr?.message || tokenErr);
      }
      
      if (totalTokens > 1000000) {
        threadId = await handleTokenLimit(phoneNumber, threadId, formattedMessage);
      } else {
        await openaiService.addMessageWithRetry(threadId, formattedMessage);
      }

      // Processar com OpenAI
      const whatsappData = {
        phoneNumberId: phoneNumberId,
        recipientNumber: message.from
      };

      const assistantResponse = await openaiService.runAssistant(threadId, whatsappData);

      // Armazenar resposta do assistente
      await redisService.storeMessageInConversation(phoneNumber, threadId, {
        role: 'assistant',
        content: assistantResponse,
        timestamp: Date.now()
      });

      // Enviar resposta
      await whatsappService.sendReplyWithTimeout(
        phoneNumberId,
        config.whatsapp.graphApiToken,
        message.from,
        assistantResponse,
        res
      );
    } catch (error) {
      console.error('Erro ao processar mensagens em buffer:', error);
      try {
        await whatsappService.sendSplitReply(
          phoneNumberId,
          config.whatsapp.graphApiToken,
          message.from,
          'Tive um problema temporário ao responder. Pode repetir sua última mensagem?',
          res
        );
      } catch (fallbackErr) {
        console.error('Erro ao enviar mensagem de fallback:', fallbackErr);
        if (!res.headersSent) {
          res.sendStatus(200);
        }
      }
    }
  }, 4000));
}

async function handleAudioMessage(message, phoneNumber, profileName, phoneNumberId, res, threadId) {
  const mediaId = message.audio.id;
  
  if (!mediaId) {
    console.error("Media ID is undefined");
    return;
  }

  const audioUrl = await mediaService.fetchMediaUrl(mediaId);
  const audioContent = await mediaService.downloadAudio(audioUrl);
  const { transcription, language } = await audioService.transcribeAudio(audioContent);

  if (!transcription) {
    await whatsappService.sendSplitReply(
      phoneNumberId,
      config.whatsapp.graphApiToken,
      message.from,
      "Desculpe, por enquanto não consigo ouvir seu áudio, poderia escrever?",
      res
    );
    return;
  }

  // Verificar se deve responder com texto ou áudio
  const shouldRespondWithText = transcription.toLowerCase().includes('link') || 
                                transcription.toLowerCase().includes('site');

  // Processar transcrição
  const transcriptionWithContext = `[Usuário ${profileName} enviou áudio dizendo:] ${transcription}`;
  await openaiService.addMessageToThread(threadId, transcriptionWithContext);
  await redisService.storeMessageInConversation(phoneNumber, threadId, {
    role: 'user',
    content: transcriptionWithContext,
    timestamp: Date.now()
  });

  const whatsappData = {
    phoneNumberId: phoneNumberId,
    recipientNumber: message.from
  };

  const assistantResponse = await openaiService.runAssistant(threadId, whatsappData);

  await redisService.storeMessageInConversation(phoneNumber, threadId, {
    role: 'assistant',
    content: assistantResponse,
    timestamp: Date.now()
  });

  // Enviar resposta
  if (shouldRespondWithText) {
    await whatsappService.sendSplitReply(
      phoneNumberId,
      config.whatsapp.graphApiToken,
      message.from,
      assistantResponse,
      res
    );
  } else {
    await whatsappService.sendReply(
      phoneNumberId,
      config.whatsapp.graphApiToken,
      message.from,
      assistantResponse,
      res,
      true
    );
  }
}

async function handleImageMessage(message, phoneNumber, profileName, phoneNumberId, res, threadId) {
  const mediaId = message.image.id;
  const caption = message.image.caption || "";

  if (!mediaId) {
    console.error("Media ID is undefined");
    return;
  }

  const imageUrl = await mediaService.fetchMediaUrl(mediaId);
  console.log("Image URL:", imageUrl);

  // Enviar mensagem de confirmação
  await whatsappService.sendSplitReply(
    phoneNumberId,
    config.whatsapp.graphApiToken,
    message.from,
    "Recebi sua foto. Por favor, aguarde alguns instantes enquanto eu analiso! 🕵🔍",
    res
  );

  const description = await mediaService.processImage(imageUrl, caption);

  if (description) {
    const instruction = `[Usuário ${profileName} enviou uma imagem]\n\nEssa é a descrição da imagem foi enviada por uma outra IA para você, Ultron. Use essa descrição para gerar sua resposta. Lembre-se essa mensagem foi enviada por outra IA, não pelo usuário. Use essas informações para gerar uma resposta para ser enviada ao usuário ${profileName}. Essa é a descrição da imagem e legenda que o usuário incluiu (se houver): ${description}`;

    await redisService.storeMessageInConversation(phoneNumber, threadId, {
      role: 'user',
      content: instruction,
      timestamp: Date.now()
    });

    await openaiService.addMessageWithRetry(threadId, instruction);

    const whatsappData = {
      phoneNumberId: phoneNumberId,
      recipientNumber: message.from
    };

    const assistantResponse = await openaiService.runAssistant(threadId, whatsappData);

    await redisService.storeMessageInConversation(phoneNumber, threadId, {
      role: 'assistant',
      content: assistantResponse,
      timestamp: Date.now()
    });

    await whatsappService.sendReplyWithTimeout(
      phoneNumberId,
      config.whatsapp.graphApiToken,
      message.from,
      assistantResponse,
      res
    );
  }
}

async function handlePdfMessage(message, phoneNumber, profileName, phoneNumberId, res, threadId) {
  const mediaId = message.document.id;
  const mediaUrl = await mediaService.fetchMediaUrl(mediaId);

  // Enviar mensagem de confirmação
  await whatsappService.sendSplitReply(
    phoneNumberId,
    config.whatsapp.graphApiToken,
    message.from,
    "Um momento, vou analisar o documento enviado.🕵🏻‍♂️🔍",
    res
  );

  const pdfContent = await mediaService.downloadPdf(mediaUrl);
  const extractedText = await mediaService.extractTextFromPdf(pdfContent);

  const instruction = `Este é o texto do arquivo enviado. Responda de forma didática.`;
  const content = `${instruction}\n\nTexto extraído do PDF:\n${extractedText}`;

  await openaiService.addMessageToThread(threadId, content);

  await redisService.storeMessageInConversation(phoneNumber, threadId, {
    role: 'user',
    content: content,
    timestamp: Date.now()
  });

  await whatsappService.sendSplitReply(
    phoneNumberId,
    config.whatsapp.graphApiToken,
    message.from,
    "Documento analisado, já podemos falar sobre ele.",
    res
  );
}

async function handleDeleteThreadCommand(phoneNumber, phoneNumberId, from, res) {
  const threadId = await redisService.getThreadId(phoneNumber);

  if (threadId) {
    try {
      await openaiService.deleteThread(threadId);
      console.log(`Thread ${threadId} deletado no OpenAI.`);
    } catch (error) {
      console.error(`Erro ao deletar thread no OpenAI:`, error);
    }

    await redisService.deleteThreadId(phoneNumber);
    
    await whatsappService.sendSplitReply(
      phoneNumberId,
      config.whatsapp.graphApiToken,
      from,
      "Thread ID apagado com sucesso.",
      res
    );
  } else {
    await whatsappService.sendReply(
      phoneNumberId,
      config.whatsapp.graphApiToken,
      from,
      "Nenhum thread ID encontrado para apagar.",
      res
    );
  }
}

async function handleTokenLimit(phoneNumber, threadId, formattedMessage) {
  console.log(`Total de tokens excedeu 1.000.000 para o thread ${threadId}. Resumindo contexto...`);
  
  const summarizedContext = await openaiService.summarizeContext(threadId);
  const newThread = await openaiService.createThreadWithSummary(phoneNumber, summarizedContext);
  const newThreadId = newThread.id;
  
  await redisService.setThreadId(phoneNumber, newThreadId);
  console.log(`Novo thread ID ${newThreadId} criado com contexto resumido para ${phoneNumber}`);
  
  await openaiService.addMessageToThread(newThreadId, formattedMessage);
  
  return newThreadId;
}

// Função para resetar memória de um usuário específico
export const resetUserMemory = async (phoneNumber, phoneNumberId, res) => {
  try {
    console.log(`🔄 Iniciando reset de memória para: ${phoneNumber}`);
    
    // Resetar memória no Redis e OpenAI
    await redisService.resetUserMemory(phoneNumber);
    
    // Enviar confirmação para o usuário
    await whatsappService.sendReply(
      phoneNumberId,
      config.whatsapp.graphApiToken,
      phoneNumber,
      "🧹 *Memória resetada com sucesso!*\n\nAgora posso começar uma nova conversa do zero. Como posso te ajudar?",
      res
    );
    
    console.log(`✅ Memória resetada para ${phoneNumber}`);
    
  } catch (error) {
    console.error(`❌ Erro ao resetar memória para ${phoneNumber}:`, error);
    
    // Enviar mensagem de erro
    await whatsappService.sendReply(
      phoneNumberId,
      config.whatsapp.graphApiToken,
      phoneNumber,
      "❌ Ocorreu um erro ao resetar a memória. Tente novamente em alguns instantes.",
      res
    );
  }
};

// Função para lidar com respostas de onboarding
const handleOnboardingResponse = async (phoneNumber, phoneNumberId, userMessage, res) => {
  try {
    const consentGiven = userMessage.includes('sim') || userMessage.includes('autorizo') || 
                        userMessage.includes('✅') || userMessage.includes('yes');
    
    await onboardingService.handleConsentResponse(phoneNumber, consentGiven);
    
  } catch (error) {
    console.error('Error handling onboarding response:', error);
  }
};

// Função para lidar com solicitação de início do serviço
const handleStartRequest = async (phoneNumber, phoneNumberId, profileName, res) => {
  try {
    console.log(`🚀 Usuário ${phoneNumber} solicitou início do serviço`);
    
    // Verificar status de pagamento
    const paymentStatus = await paymentService.checkPaymentStatus(phoneNumber);
    
    if (paymentStatus.hasPayment) {
      console.log(`✅ Pagamento confirmado para ${phoneNumber}, iniciando onboarding`);
      
      // Verificar se já está em onboarding
      const onboardingStatus = await onboardingService.getOnboardingStatus(phoneNumber);
      if (onboardingStatus && onboardingStatus.status === 'completed') {
        await whatsappService.sendReply(
          phoneNumberId,
          config.whatsapp.graphApiToken,
          phoneNumber,
          `Olá ${profileName}! 😊\n\nVocê já completou o onboarding e tem acesso completo ao assistente nutricional!\n\nComo posso te ajudar hoje?`
        );
        return;
      }
      
      // Iniciar onboarding
      await onboardingService.startOnboarding(phoneNumber, null, profileName);
      
    } else {
      console.log(`❌ Pagamento não encontrado para ${phoneNumber}, enviando mensagem de pagamento necessário`);
      
      // Enviar mensagem de pagamento necessário com link dinâmico
      const paymentMessage = await paymentService.getPaymentRequiredMessageWithLink(phoneNumber);
      await whatsappService.sendReply(
        phoneNumberId,
        config.whatsapp.graphApiToken,
        phoneNumber,
        paymentMessage
      );
    }
    
  } catch (error) {
    console.error('Erro ao processar solicitação de início:', error);
    
    // Enviar mensagem de erro
    await whatsappService.sendReply(
      phoneNumberId,
      config.whatsapp.graphApiToken,
      phoneNumber,
      "❌ Ocorreu um erro ao processar sua solicitação. Tente novamente em alguns instantes."
    );
  }
};

// Função para lidar com solicitação de plano específico
const handlePlanRequest = async (phoneNumber, phoneNumberId, planType, res) => {
  try {
    console.log(`💳 Usuário ${phoneNumber} solicitou plano: ${planType}`);
    
    // Verificar status de pagamento primeiro
    const paymentStatus = await paymentService.checkPaymentStatus(phoneNumber);
    
    if (paymentStatus.hasPayment) {
      console.log(`✅ Usuário ${phoneNumber} já tem pagamento, enviando mensagem de boas-vindas`);
      
      await whatsappService.sendReply(
        phoneNumberId,
        config.whatsapp.graphApiToken,
        phoneNumber,
        `🎉 Você já tem uma assinatura ativa!\n\nDigite "Quero iniciar" para começar a usar o assistente nutricional.`
      );
      return;
    }
    
    // Enviar mensagem com plano específico
    const planMessage = paymentService.getSpecificPlanMessage(planType, phoneNumber);
    await whatsappService.sendReply(
      phoneNumberId,
      config.whatsapp.graphApiToken,
      phoneNumber,
      planMessage
    );
    
  } catch (error) {
    console.error('Erro ao processar solicitação de plano:', error);
    
    // Enviar mensagem de erro
    await whatsappService.sendReply(
      phoneNumberId,
      config.whatsapp.graphApiToken,
      phoneNumber,
      "❌ Ocorreu um erro ao processar sua solicitação. Tente novamente em alguns instantes."
    );
  }
};