// services\redisService.js

import { redisClient } from '../config/redis.js';

// Funções para gerenciar thread IDs
export async function getThreadId(phoneNumber) {
  return await redisClient.get(`threadId:${phoneNumber}`);
}

export async function setThreadId(phoneNumber, threadId) {
  return await redisClient.set(`threadId:${phoneNumber}`, threadId);
}

export async function deleteThreadId(phoneNumber) {
  return await redisClient.del(`threadId:${phoneNumber}`);
}

// Funções para gerenciar mensagens
export async function getMessageData(messageId) {
  return await redisClient.hGetAll(`message:${messageId}`);
}

export async function saveMessage(messageId, messageData) {
  console.log("Storing message in Redis:", messageData);

  return await redisClient.hSet(`message:${messageId}`, {
    id: messageData.id,
    timestamp: messageData.timestamp,
    phoneNumber: messageData.phoneNumber,
    content: messageData.content,
    assistantId: messageData.assistantId,
    aiPhoneNumber: messageData.aiPhoneNumber,
    threadId: messageData.threadId,
    createdAt: messageData.createdAt,
    localTime: messageData.localTime,
    location: JSON.stringify(messageData.location),
    type: messageData.type,
    status: messageData.status,
    isAutoGenerated: JSON.stringify(messageData.isAutoGenerated),
    deviceInfo: JSON.stringify(messageData.deviceInfo),
    userName: messageData.userName
  });
}

// Função para armazenar mensagens em conversações
export async function storeMessageInConversation(phoneNumber, threadId, messageData) {
  const key = `conversation:${phoneNumber}:${threadId}`;
  return await redisClient.rPush(key, JSON.stringify(messageData));
}

// Função para recuperar conversação
export async function getConversation(phoneNumber, threadId) {
  const key = `conversation:${phoneNumber}:${threadId}`;
  const messages = await redisClient.lRange(key, 0, -1);
  return messages.map(msg => JSON.parse(msg));
}

// Função para limpar conversação
export async function clearConversation(phoneNumber, threadId) {
  const key = `conversation:${phoneNumber}:${threadId}`;
  return await redisClient.del(key);
}

// Função para verificar se existe uma mensagem
export async function messageExists(messageId) {
  return await redisClient.exists(`message:${messageId}`);
}

// Função para obter todas as thread IDs
export async function getAllThreadIds() {
  const keys = await redisClient.keys('threadId:*');
  const threadIds = {};
  
  for (const key of keys) {
    const phoneNumber = key.replace('threadId:', '');
    threadIds[phoneNumber] = await redisClient.get(key);
  }
  
  return threadIds;
}

// Função para salvar estado temporário
export async function saveTemporaryState(key, value, expireSeconds = 3600) {
  await redisClient.setEx(`temp:${key}`, expireSeconds, JSON.stringify(value));
}

// Função para obter estado temporário
export async function getTemporaryState(key) {
  const value = await redisClient.get(`temp:${key}`);
  return value ? JSON.parse(value) : null;
}

// Função para deletar estado temporário
export async function deleteTemporaryState(key) {
  return await redisClient.del(`temp:${key}`);
}

// Função para resetar completamente a memória de um número
export async function resetUserMemory(phoneNumber) {
  try {
    console.log(`🔄 Resetando memória para o número: ${phoneNumber}`);
    
    // 1. Obter thread ID atual
    const threadId = await getThreadId(phoneNumber);
    
    // 2. Deletar thread ID do Redis
    await deleteThreadId(phoneNumber);
    
    // 3. Limpar conversação se thread ID existir
    if (threadId) {
      await clearConversation(phoneNumber, threadId);
      
      // 4. Deletar thread da OpenAI
      try {
        const { deleteThread } = await import('./openaiService.js');
        await deleteThread(threadId);
        console.log(`✅ Thread ${threadId} deletado da OpenAI`);
      } catch (error) {
        console.error('Erro ao deletar thread da OpenAI:', error.message);
      }
    }
    
    // 5. Limpar todas as conversações do número (caso haja múltiplas)
    const conversationKeys = await redisClient.keys(`conversation:${phoneNumber}:*`);
    for (const key of conversationKeys) {
      await redisClient.del(key);
    }
    
    // 6. Limpar mensagens individuais do número
    const messageKeys = await redisClient.keys(`message:*`);
    for (const key of messageKeys) {
      const messageData = await redisClient.hGetAll(key);
      if (messageData.phoneNumber === phoneNumber) {
        await redisClient.del(key);
      }
    }
    
    // 7. Limpar estados temporários do número
    const tempKeys = await redisClient.keys(`temp:${phoneNumber}*`);
    for (const key of tempKeys) {
      await redisClient.del(key);
    }
    
    console.log(`✅ Memória resetada com sucesso para ${phoneNumber}`);
    return true;
    
  } catch (error) {
    console.error(`❌ Erro ao resetar memória para ${phoneNumber}:`, error);
    throw error;
  }
}